# MIT License: https://gitlab.com/pages/hugo/blob/master/LICENSE
# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  - "wget -S --header=\"Authorization: Bearer $CLOUDFLARE_API_KEY\" --header=\"Content-Type: application/json\" --post-data '{\"purge_everything\":true}' \"https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache\""
  artifacts:
    paths:
    - public
  only:
  - master
