baseURL = "https://blog.ctmartin.me/"
copyright = "2019 Christian Martin"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
theme = ["ctmartin"]
title = "Christian Martin's Blog"

[permalinks]
  blog = "/:year/:month/:slug/"

[[menu.main]]
    name = "Posts"
    idenfifier = "posts"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Portfolio"
    idenfifier = "portfolio"
    url = "https://ctmartin.me/"
    weight = 20
[[menu.main]]
    name = "About"
    idenfifier = "about"
    url = "https://ctmartin.me/about"
    weight = 30