baseURL = "https://blog.ctmartin.me/"
copyright = "© 2020 Christian Martin"
disableHugoGeneratorInject = true
enableEmoji = true
languageCode = "en-us"
paginatePath = ""
theme = ["ctmartin"]
title = "Christian Martin's Blog"

[Authors.ctmartin]
  given_name = "Christian"
  family_name = "Martin"
  display_name = "Christian Martin"
[Authors.ctmartin.social]
    website = "https://ctmartin.dev/"
    github = "ct-martin"
    twitter = "_ctmartin"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false

[[menu.main]]
    name = "Posts"
    idenfifier = "posts"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Tags"
    idenfifier = "tags"
    url = "/tags"
    weight = 11
[[menu.main]]
    name = "Portfolio"
    idenfifier = "portfolio"
    url = "https://ctmartin.dev/"
    weight = 20
[[menu.main]]
    name = "About"
    idenfifier = "about"
    url = "https://ctmartin.dev/about"
    weight = 30

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML", "AMP"]
  section = ["HTML", "AMP", "RSS"]
  taxonomy = ["HTML", "AMP", "RSS"]
  taxonomyTerm = ["HTML", "AMP", "RSS"]
#  page = ["HTML", "AMP", "JSON"]
#  section = ["HTML", "RSS", "AMP", "JSON"]
#  taxonomy = ["HTML", "RSS", "AMP", "JSON"]
#  taxonomyTerm = ["HTML", "RSS", "AMP", "JSON"]
  

[params]
  author = "Christian Martin"
  authorLinks = ["https://ctmartin.dev/", "https://github.com/ct-martin", "https://gitlab.com/ctmartin", "https://twitter.com/_ctmartin"]
  description = "Christian Martin's Blog"
  sourceurl = "https://github.com/ct-martin/blog.ctmartin.me/"

[permalinks]
  blog = "/:year/:month/:filename/"

[Social]
  twitter = "_ctmartin"