baseURL = "https://blog.ctmartin.me/"
copyright = "© 2019 Christian Martin"
disableHugoGeneratorInject = true
languageCode = "en-us"
paginatePath = ""
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
#pygmentsOptions = "linenos=true"
pygmentsUseClasses = true
theme = ["ctmartin"]
title = "Christian Martin's Blog"

[blackfriday]
  fractions = false

[Authors.ctmartin]
  given_name = "Christian"
  family_name = "Martin"
  display_name = "Christian Martin"
[Authors.ctmartin.social]
    website = "https://ctmartin.dev/"
    github = "ct-martin"
    twitter = "_ctmartin"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP"]

[params]
  author = "Christian Martin"
  authorLinks = ["https://ctmartin.dev/", "https://github.com/ct-martin", "https://gitlab.com/ctmartin", "https://twitter.com/_ctmartin"]
  description = "Christian Martin's Blog"
  sourceurl = "https://github.com/ct-martin/blog.ctmartin.me/"

[permalinks]
  blog = "/:year/:month/:filename/"

[[menu.main]]
    name = "Posts"
    idenfifier = "posts"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Tags"
    idenfifier = "tags"
    url = "/tags"
    weight = 11
[[menu.main]]
    name = "Portfolio"
    idenfifier = "portfolio"
    url = "https://ctmartin.dev/"
    weight = 20
[[menu.main]]
    name = "About"
    idenfifier = "about"
    url = "https://ctmartin.dev/about"
    weight = 30
